# Learn more about services, parameters and containers at
# https://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    AppBundle\:
        resource: '../../src/AppBundle/*'
        exclude: '../../src/AppBundle/{Entity,Repository,Tests}'

    AppBundle\Controller\:
        resource: '../../src/AppBundle/Controller'
        public: true
        tags: ['controller.service_arguments']

### Listeners

    app.listener.send.bot.response:
        class: AppBundle\Listener\SendBotResponseListener
        arguments: ['@app.buzz.browser']
        tags:
            - { name: kernel.event_listener, event: bot.response }

    app.listener.bot.logger:
        class: AppBundle\Listener\BotLoggerListener
        arguments: ['@logger']
        tags:
            - { name: monolog.logger, channel: bot }
            - { name: kernel.event_listener, event: bot.log.response, method: 'onBotResponse' }
            - { name: kernel.event_listener, event: bot.log.request, method: 'onBotRequest' }

### Bot Clients

    app.bot.client.facebook:
        class: AppBundle\Service\BotClient\FacebookBotClient
        public: true
        arguments: ['@request_stack', '@event_dispatcher','%facebook_access_token%']
        tags:
            - { name: bot.client, alias: facebook}

####
    app.buzz.browser:
        class: Buzz\Browser
        public: false
        arguments: []
