# Learn more about services, parameters and containers at
# https://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    AppBundle\:
        resource: '../../src/AppBundle/*'
        exclude: '../../src/AppBundle/{Entity,Repository,Tests}'

    AppBundle\Controller\:
        resource: '../../src/AppBundle/Controller'
        public: true
        tags: ['controller.service_arguments']

### Listeners

    app.listener.send.bot.response:
        class: AppBundle\Listener\SendBotResponseListener
        arguments: ['@app.buzz.browser']
        tags:
            - { name: kernel.event_listener, event: bot.response }

    app.listener.bot.logger:
        class: AppBundle\Listener\BotLoggerListener
        arguments: ['@logger']
        tags:
            - { name: monolog.logger, channel: bot }
            - { name: kernel.event_listener, event: bot.log.response, method: 'onBotResponse' }
            - { name: kernel.event_listener, event: bot.log.request, method: 'onBotRequest' }
            - { name: kernel.event_listener, event: bot.log.message, method: 'onBotMessage' }

### Bot Clients

    AppBundle\Service\BotClient\FacebookBotClient:
        public: true
        arguments: ['', '@event_dispatcher','%facebook_access_token%']
        tags:
            - { name: bot.client, alias: facebook}


### Bot Request Strategy

    app.bot.request.strategy.postback:
        class: AppBundle\Model\BotRequest\FacebookBotRequest\Strategy\FbPostBackStrategy
        public: false
        tags:
            - { name: bot.request.strategy.facebook, order: 10}

    app.bot.request.strategy.quick_reply:
        class: AppBundle\Model\BotRequest\FacebookBotRequest\Strategy\FbQuickReplyStrategy
        public: false
        tags:
            - { name: bot.request.strategy.facebook, order: 20}

    app.bot.request.strategy.text:
        class: AppBundle\Model\BotRequest\FacebookBotRequest\Strategy\FbTextStrategy
        public: false
        tags:
           - { name: bot.request.strategy.facebook, order: 30}

####
    app.buzz.browser:
        class: Buzz\Browser
        public: false
        arguments: []
